"use client";

import Link from "next/link";
import React, { useState } from "react";

const accordianData = [
  {
    title: "What is TokScript?",
    content:
      "TokScript is an AI-powered platform that allows users to generate transcripts for TikTok, Instagram Reels, and YouTube Shorts videos. It offers features like bulk importing, MCP integration with Claude and ChatGPT, team collaboration, and AI agents to enhance content creation and management.",
  },
  {
    title: "Who can use TokScript?",
    content:
      "TokScript is designed for content creators, social media managers, marketing teams, agencies, and businesses who want to streamline their video content creation process. Whether you're a solo creator or part of a large team, our platform scales to meet your needs.",
  },
  {
    title: "How does TokScript work?",
    content:
      "Simply upload your video links or import them in bulk, and our AI analyzes the content to generate engaging scripts. You can then customize, save to your cloud library, and share with your team. Our AI agents can also help optimize scripts for better engagement and virality.",
  },
  {
    title: "Can I customize the scripts?",
    content:
      "Absolutely! All generated scripts are fully customizable. You can edit, rewrite, add your own style, and save multiple versions. Our platform also offers AI-powered suggestions to help you optimize your scripts for maximum engagement.",
  },
  {
    title: "Does TokScript only work for TikTok?",
    content:
      "No, TokScript works across multiple platforms including TikTok, Instagram Reels, and YouTube Shorts. Our AI is trained to understand the unique requirements and audience preferences of each platform to generate optimized content.",
  },
  {
    title: "Are the scripts original?",
    content:
      "Yes, all scripts generated by TokScript are original content created by our AI based on your input videos. We ensure that each script is unique and tailored to your specific content, helping you maintain authenticity while saving time on content creation.",
  },
  {
    title: "How long does it take to download a transcript?",
    content:
      "The download time for videos transcripts depends on various factors: internet speed, the length of the transcript, and the size or length of the video files. Generally, it should take about 5-10 seconds to get download the video transcript. If the video is longer (5 minutes) it can take around 30 seconds until it's complete. Please note that these are approximate times and may vary based on the specific circumstances mentioned above.",
  },
  {
    title: "How do I download TikTok Video Transcript?",
    content:
      'We make it easy to download your TikTok Video Transcript instantly and with as little effort as possible. To download your TikTok video Transcript all you need is the link to the video you wish to get the transcript from. Go to the TikTok video you wish to download, Copy the link to the video, and paste it into the input field up above. This will allow you to download the TikTok video transcript instantly! You can grab this link by going to the "share" icon, and clicking "Copy Link". Now just paste it on our site and that\'s it!',
  },
  {
    title: "How do I download Instagram Reels Video Transcript?",
    content:
      'In order to download your Instagram Reels video Transcript all you need is the link to the video. Go to the Instagram Reels video you wish to download, Copy the link to the video, and paste it into the input field on our website. This will allow you to download the Instagram Reels video transcript instantly! You can grab this link by going to the "share" icon, and clicking "Copy Link". Now just paste it on our site and that\'s it!',
  },
  {
    title: "How do I download Youtube Shorts video transcript?",
    content:
      'It\'s simple! All you need to do is go to the Youtube Shorts video you wish to download, Copy the link to the video, and paste it into the input field on our website. This will allow you to download the Youtube Shorts video transcript instantly! You can grab this link by going to the "share" icon, and clicking "Copy Link". Now just paste it on our site and that\'s it!',
  },
  {
    title: "It says there's no transcripts to download, how come?",
    content:
      "If you get this error it means that the video you tried to get a transcription from doesn't exist. This has nothing to do with our website and more so to do with the specific video you're attempting to download. Double-check and make sure that something is being said in the video in order for us to extract those words and download them for you!",
  },
  {
    title: "Will it download ANY transcript from ANY video?",
    content:
      "We can download ANY transcript from ANY video for TikTok, Youtube Shorts, and IG Reels so long as there's a transcript available to download. If your video has no \"talking\" in it, or the creator has disabled the auto-transcribe within the platform itself we will not be able to download them. Don't worry, most videos have video transcripts enabled and this only happens on rare occasions.",
  },
  {
    title:
      "Do I need to have a TikTok, Youtube, or Instagram account to download transcripts?",
    content:
      'Absolutely not! You don\'t need a TikTok, Instagram, or Youtube account to download your video transcripts. All you require is the link to the video you want to download the transcript from. Simply paste your link into the input field at the top of this page and hit "Start." and we will handle the rest!',
  },
  {
    title:
      "Do I need to be logged into a TikTok, Youtube, or Instagram to download Transcripts?",
    content:
      "No. You do not need to be logged into TikTok, Instagram, or Youtube when downloading the transcripts. Making it fast and easy for you to use regardless where you're at or if you're logged in.",
  },
  {
    title: "Do I need to install extensions to use the downloader?",
    content:
      "No. To save your video transcripts all you need to do is add the link to your TikTok, Youtube Shorts, or Instagram Reels video. Just paste it into the input field above and download your video transcript!",
  },
  {
    title:
      "How do I get the link to download TikTok, Instagram Reels, or Youtube Shorts transcripts?",
    content:
      "To download Youtube Shorts, TikTok Videos, and IG Reels is simple! All you need is the link to the video (available on both desktop and mobile). Copy paste it into our site and we'll take care of the rest! It's that simple to download any video transcript with ease!",
  },
  {
    title: "Do I have to pay to download transcripts?",
    content:
      "This website is 100% free for you to use. We do have a paid subscription that gives you over 10 different features that a free account does not have! If you like this tool we suggest checking out our other tools and extensions for even faster social media growth and management. We support and are compatible with all browsers such as Google Chrome, Arc, Mozilla Firefox, Microsoft Edge, Safari, and more!",
  },
  {
    title: "Is it free?",
    content:
      "Yes! TikTok, Instagram Reels, and YouTube Shorts offer free video transcripts. These transcripts are created using automated speech recognition technology, so they might not be entirely accurate but are generally suitable for most purposes.",
  },
];

export default function FaqSection({ faqData, title, subtitle, bottomText }) {
  const dataToRender = faqData || accordianData;
  const [openFaq, setOpenFaq] = useState(null);

  return (
    <section className="ts-faq-mcp" id="faqs">
      <div className="ts-faq-mcp-wrap">
        <div className="ts-faq-mcp-header">
          <span className="ts-faq-mcp-eyebrow">FAQ</span>
          <div className="ts-faq-mcp-headings">
            <h2>{title || "Frequently Asked Questions"}</h2>
            <p>
              {subtitle ||
                "The power isn't in individual tools. It's in chaining them together in a single conversation."}
            </p>
          </div>
        </div>

        <div className="ts-faq-mcp-list">
          {dataToRender.map((item, index) => {
            const isOpen = openFaq === index;
            return (
              <div className="ts-faq-mcp-item" key={index}>
                <button
                  type="button"
                  className={`ts-faq-mcp-q${isOpen ? " open" : ""}`}
                  onClick={() => setOpenFaq(isOpen ? null : index)}
                  aria-expanded={isOpen}
                >
                  {item.title}
                  <span className="ts-faq-mcp-icon" aria-hidden>+</span>
                </button>
                <div className={`ts-faq-mcp-a${isOpen ? " open" : ""}`}>
                  {item.content}
                </div>
              </div>
            );
          })}
        </div>

        <div className="ts-faq-mcp-cta">
          <p className="ts-faq-mcp-cta-text">Still have questions?</p>
          <Link
            href="https://help.tokscript.com/"
            target="_blank"
            rel="noopener noreferrer"
            className="ts-faq-mcp-cta-btn"
          >
            Visit Help Center
          </Link>
        </div>
      </div>
    </section>
  );
}
